development: localhost:6379
test: localhost:6379
staging: redis1.example.com:6379
fi: localhost:6379
#production: redis1.example.com:6379
production: redis://h:pd92sc2rioockooca7i8j25n3s@ec2-107-22-210-83.compute-1.amazonaws.com:13459